spring.application.name=EDSTEM
server.port=8081

# Datasource configuration
spring.datasource.url=${DB_CONNECTION}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=restaurant
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springdoc=DEBUG
logging.level.org.springdoc.webmvc.api.OpenApiResource=DEBUG
logging.level.org.springframework.web.servlet.resource=ERROR


DB_CONNECTION=jdbc:postgresql://localhost:5432/edstem
DB_USERNAME=postgres
DB_PASSWORD=vIn!9673140